//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyContractsGenerator.Common.I18N {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyContractsGenerator.Common.I18N.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Administrator&apos;s organization : .
        /// </summary>
        public static string Administrateur_Organization {
            get {
                return ResourceManager.GetString("Administrateur_Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You are goin to add a new administrator to your project, do you want to continue ? An email with a generated password will be send to this administrator..
        /// </summary>
        public static string Administrator_AddConfirmationMessage {
            get {
                return ResourceManager.GetString("Administrator_AddConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Administrator &quot;{0}&quot; successfully created.
        /// </summary>
        public static string Administrator_Added {
            get {
                return ResourceManager.GetString("Administrator_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Yes.
        /// </summary>
        public static string Administrator_AddValidateButton {
            get {
                return ResourceManager.GetString("Administrator_AddValidateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        public static string Administrator_CancelButton {
            get {
                return ResourceManager.GetString("Administrator_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to cancel the modifications?.
        /// </summary>
        public static string Administrator_CancelModal_Message {
            get {
                return ResourceManager.GetString("Administrator_CancelModal_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Current password.
        /// </summary>
        public static string Administrator_CurrentPassword {
            get {
                return ResourceManager.GetString("Administrator_CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit administrator.
        /// </summary>
        public static string Administrator_Edit {
            get {
                return ResourceManager.GetString("Administrator_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Administrator &quot;{0}&quot; successfully edited.
        /// </summary>
        public static string Administrator_Edited {
            get {
                return ResourceManager.GetString("Administrator_Edited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email.
        /// </summary>
        public static string Administrator_Email {
            get {
                return ResourceManager.GetString("Administrator_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Incorrect email format.
        /// </summary>
        public static string Administrator_ErrorIncorrectEmail {
            get {
                return ResourceManager.GetString("Administrator_ErrorIncorrectEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This e-mail address is already in use.
        /// </summary>
        public static string Administrator_ErrorIncorrectEmailAlreadyUsed {
            get {
                return ResourceManager.GetString("Administrator_ErrorIncorrectEmailAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Incorrect password.
        /// </summary>
        public static string Administrator_ErrorIncorrectPassword {
            get {
                return ResourceManager.GetString("Administrator_ErrorIncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Passwords are not the same.
        /// </summary>
        public static string Administrator_ErrorIncorrectPasswordConfirmation {
            get {
                return ResourceManager.GetString("Administrator_ErrorIncorrectPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The user {0} is unknown from the system.
        /// </summary>
        public static string Administrator_ErrorMessage_UnknownUser {
            get {
                return ResourceManager.GetString("Administrator_ErrorMessage_UnknownUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The new and old password cannot be the same..
        /// </summary>
        public static string Administrator_ErrorOldAndNewPasswordAreTheSame {
            get {
                return ResourceManager.GetString("Administrator_ErrorOldAndNewPasswordAreTheSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Firstname.
        /// </summary>
        public static string Administrator_FirstName {
            get {
                return ResourceManager.GetString("Administrator_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dear {0}, &lt;br/&gt;&lt;br/&gt; This email notify you that a password has been generated for your MyContractsGenerator account ({1}). &lt;br/&gt;&lt;br/&gt;Company : {2}&lt;br/&gt;Your email (login) : {3} &lt;br/&gt;Your new password : &lt;b&gt;{4}&lt;/b&gt;&lt;br/&gt;&lt;br/&gt;Don&apos;t forget to change your password after your first login (&quot;My profile&quot; section)&lt;br/&gt;&lt;br/&gt;Have a good day,&lt;br/&gt;MyContractsGenerator Team..
        /// </summary>
        public static string Administrator_GeneratedAdministratorPasswordBody {
            get {
                return ResourceManager.GetString("Administrator_GeneratedAdministratorPasswordBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MyContractsGenerator - A new password has been generated for you..
        /// </summary>
        public static string Administrator_GeneratedAdministratorPasswordTitle {
            get {
                return ResourceManager.GetString("Administrator_GeneratedAdministratorPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Generate a new password.
        /// </summary>
        public static string Administrator_GenerateNewPassword {
            get {
                return ResourceManager.GetString("Administrator_GenerateNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Administrators.
        /// </summary>
        public static string Administrator_label {
            get {
                return ResourceManager.GetString("Administrator_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lastname.
        /// </summary>
        public static string Administrator_LastName {
            get {
                return ResourceManager.GetString("Administrator_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure ?.
        /// </summary>
        public static string Administrator_Modal_Header {
            get {
                return ResourceManager.GetString("Administrator_Modal_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No.
        /// </summary>
        public static string Administrator_Modal_No {
            get {
                return ResourceManager.GetString("Administrator_Modal_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Yes.
        /// </summary>
        public static string Administrator_Modal_Yes {
            get {
                return ResourceManager.GetString("Administrator_Modal_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New administrator.
        /// </summary>
        public static string Administrator_New {
            get {
                return ResourceManager.GetString("Administrator_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dear {0}, &lt;br/&gt;&lt;br/&gt; This email notify you a password change related to your MyContractsGenerator account ({1}). &lt;br/&gt;&lt;br/&gt;Your company : {2}&lt;br/&gt;Your email (login) : {3} &lt;br/&gt;&lt;br/&gt;Have a good day,&lt;br/&gt;MyContractsGenerator Team..
        /// </summary>
        public static string Administrator_NewAdministratorPasswordBody {
            get {
                return ResourceManager.GetString("Administrator_NewAdministratorPasswordBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MyContractsGenerator - Password Changed.
        /// </summary>
        public static string Administrator_NewAdministratorPasswordTitle {
            get {
                return ResourceManager.GetString("Administrator_NewAdministratorPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New Password.
        /// </summary>
        public static string Administrator_NewPassword {
            get {
                return ResourceManager.GetString("Administrator_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New password confirmation.
        /// </summary>
        public static string Administrator_NewPasswordConfirmation {
            get {
                return ResourceManager.GetString("Administrator_NewPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A new password has been generated for {0}. The new password has been sent by email to the administrator..
        /// </summary>
        public static string Administrator_NewPasswordGenerated {
            get {
                return ResourceManager.GetString("Administrator_NewPasswordGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Administrators.
        /// </summary>
        public static string Administrator_PageTitle {
            get {
                return ResourceManager.GetString("Administrator_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change administrator password (optionnal).
        /// </summary>
        public static string Administrator_PasswordChange {
            get {
                return ResourceManager.GetString("Administrator_PasswordChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Administrator &quot;{0} {1}&quot; has been removed.
        /// </summary>
        public static string Administrator_RemoveNotification_Message {
            get {
                return ResourceManager.GetString("Administrator_RemoveNotification_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure ?.
        /// </summary>
        public static string Administrator_SuppressionModal_Header {
            get {
                return ResourceManager.GetString("Administrator_SuppressionModal_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to delete the administrator &quot;{0} {1}&quot; ?.
        /// </summary>
        public static string Administrator_SuppressionModal_Message {
            get {
                return ResourceManager.GetString("Administrator_SuppressionModal_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove collaborator.
        /// </summary>
        public static string Administrator_Tooltip_RemoveUser {
            get {
                return ResourceManager.GetString("Administrator_Tooltip_RemoveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Validate.
        /// </summary>
        public static string Administrator_ValidateButton {
            get {
                return ResourceManager.GetString("Administrator_ValidateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Welcome {0} ! &lt;br/&gt;&lt;br/&gt; You can now acces to the &quot;MyContractsGenerator&quot; application via your company &quot;{1}&quot;.&lt;br/&gt;URL : {2} &lt;br/&gt;Here are your credentials : &lt;br/&gt; Email (login) : {3}&lt;br/&gt;Password : &lt;b&gt;{4}&lt;/b&gt; &lt;br/&gt;&lt;br/&gt;Have a good day,&lt;br/&gt;MyContractsGenerator Team..
        /// </summary>
        public static string Administrator_WelcomeNewAdministratorBody {
            get {
                return ResourceManager.GetString("Administrator_WelcomeNewAdministratorBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MyContractsGenerator - Welcome !.
        /// </summary>
        public static string Administrator_WelcomeNewAdministratorTitle {
            get {
                return ResourceManager.GetString("Administrator_WelcomeNewAdministratorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Collaborators answers.
        /// </summary>
        public static string Answers_PageTitle {
            get {
                return ResourceManager.GetString("Answers_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Form &quot;{0}&quot; - Last update : {1}.
        /// </summary>
        public static string Answers_SubTitle {
            get {
                return ResourceManager.GetString("Answers_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Close.
        /// </summary>
        public static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You are goin to add a new collaborator to your project, do you want to continue ?.
        /// </summary>
        public static string Collaborator_AddConfirmationMessage {
            get {
                return ResourceManager.GetString("Collaborator_AddConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Collaborator &quot;{0}&quot; successfully created .
        /// </summary>
        public static string Collaborator_Added {
            get {
                return ResourceManager.GetString("Collaborator_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Yes.
        /// </summary>
        public static string Collaborator_AddValidateButton {
            get {
                return ResourceManager.GetString("Collaborator_AddValidateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Answers Count.
        /// </summary>
        public static string Collaborator_AnswerCount {
            get {
                return ResourceManager.GetString("Collaborator_AnswerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        public static string Collaborator_CancelButton {
            get {
                return ResourceManager.GetString("Collaborator_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to cancel the modifications?.
        /// </summary>
        public static string Collaborator_CancelModal_Message {
            get {
                return ResourceManager.GetString("Collaborator_CancelModal_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit collaborator.
        /// </summary>
        public static string Collaborator_Edit {
            get {
                return ResourceManager.GetString("Collaborator_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Collaborator &quot;{0}&quot; successfully edited .
        /// </summary>
        public static string Collaborator_Edited {
            get {
                return ResourceManager.GetString("Collaborator_Edited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email.
        /// </summary>
        public static string Collaborator_Email {
            get {
                return ResourceManager.GetString("Collaborator_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Incorrect email address.
        /// </summary>
        public static string Collaborator_ErrorIncorrectEmail {
            get {
                return ResourceManager.GetString("Collaborator_ErrorIncorrectEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Firstname.
        /// </summary>
        public static string Collaborator_FirstName {
            get {
                return ResourceManager.GetString("Collaborator_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Collaborators.
        /// </summary>
        public static string Collaborator_label {
            get {
                return ResourceManager.GetString("Collaborator_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lastname.
        /// </summary>
        public static string Collaborator_LastName {
            get {
                return ResourceManager.GetString("Collaborator_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New collaborateur.
        /// </summary>
        public static string Collaborator_Modal_Header {
            get {
                return ResourceManager.GetString("Collaborator_Modal_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New collaborator.
        /// </summary>
        public static string Collaborator_New {
            get {
                return ResourceManager.GetString("Collaborator_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Warning ! 
        ///You haven&apos;t created any jobs, please create some job to be able to bind them to a collaborator.
        /// </summary>
        public static string Collaborator_No_Job_Message {
            get {
                return ResourceManager.GetString("Collaborator_No_Job_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Manage your collaborators.
        /// </summary>
        public static string Collaborator_PageTitle {
            get {
                return ResourceManager.GetString("Collaborator_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Collaborator &quot;{0} {1}&quot; has been removed.
        /// </summary>
        public static string Collaborator_RemoveNotification_Message {
            get {
                return ResourceManager.GetString("Collaborator_RemoveNotification_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Collaborator&apos;s job :.
        /// </summary>
        public static string Collaborator_Role {
            get {
                return ResourceManager.GetString("Collaborator_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure ?.
        /// </summary>
        public static string Collaborator_SuppressionModal_Header {
            get {
                return ResourceManager.GetString("Collaborator_SuppressionModal_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to delete the collaborateur &quot;{0} {1}&quot; ? All linked roles will be unbind..
        /// </summary>
        public static string Collaborator_SuppressionModal_Message {
            get {
                return ResourceManager.GetString("Collaborator_SuppressionModal_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove collaborator.
        /// </summary>
        public static string Collaborator_Tooltip_RemoveUser {
            get {
                return ResourceManager.GetString("Collaborator_Tooltip_RemoveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Validate.
        /// </summary>
        public static string Collaborator_ValidateButton {
            get {
                return ResourceManager.GetString("Collaborator_ValidateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occured, please check if your informations are correct or contact your administrator..
        /// </summary>
        public static string CollaboratorForm_Error {
            get {
                return ResourceManager.GetString("CollaboratorForm_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MyContractsGenerator - Who are you ?.
        /// </summary>
        public static string CollaboratorForm_Step1_Title {
            get {
                return ResourceManager.GetString("CollaboratorForm_Step1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MyContractsGenerator - Please fill this form.
        /// </summary>
        public static string CollaboratorForm_Step2_Title {
            get {
                return ResourceManager.GetString("CollaboratorForm_Step2_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This form has been already completed, thank you, an administrator will contact you as soon as possible..
        /// </summary>
        public static string CollaboratorForm_Step3_AlreadyRepliedMessage {
            get {
                return ResourceManager.GetString("CollaboratorForm_Step3_AlreadyRepliedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Thanks for your informations, an administrator will contact you as soon as possible..
        /// </summary>
        public static string CollaboratorForm_Step3_Message {
            get {
                return ResourceManager.GetString("CollaboratorForm_Step3_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MyContractsGenerator - Thank you.
        /// </summary>
        public static string CollaboratorForm_Step3_Title {
            get {
                return ResourceManager.GetString("CollaboratorForm_Step3_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email.
        /// </summary>
        public static string Email_Label {
            get {
                return ResourceManager.GetString("Email_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occured, please try again or contact your administrator.
        /// </summary>
        public static string Error_Message {
            get {
                return ResourceManager.GetString("Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occured.
        /// </summary>
        public static string Error_Title {
            get {
                return ResourceManager.GetString("Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occured, the current page is not found..
        /// </summary>
        public static string Error404_Message {
            get {
                return ResourceManager.GetString("Error404_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 404 Error - Page not Found.
        /// </summary>
        public static string Error404_Title {
            get {
                return ResourceManager.GetString("Error404_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à First name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Available form answers : .
        /// </summary>
        public static string Form_Answers_Title {
            get {
                return ResourceManager.GetString("Form_Answers_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hello,&lt;br/&gt;&lt;br/&gt;
        ///Your company : {0}&lt;br/&gt;
        ///{1} - {2} responded to your form request.&lt;br/&gt;&lt;br/&gt;
        ///Form reponses : &lt;br/&gt; {3}&lt;br/&gt;&lt;br/&gt;
        ///Kind regards,&lt;br/&gt;
        ///MyContractsGenerator Team.
        /// </summary>
        public static string Form_CollaboratorAnswerMailBody {
            get {
                return ResourceManager.GetString("Form_CollaboratorAnswerMailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MyContractsGenerator - A new collaborator answer is available.
        /// </summary>
        public static string Form_CollaboratorAnswerMailSubject {
            get {
                return ResourceManager.GetString("Form_CollaboratorAnswerMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hello,&lt;br/&gt;&lt;br/&gt;
        ///{0} created a form for you, we need this information to complete the contract related to the company : &quot;{1}&quot;).&lt;br/&gt;
        ///Please fill this form : {2}&lt;br/&gt;&lt;br/&gt;
        ///We have generated a password : &lt;b&gt;{3}&lt;/b&gt;&lt;br/&gt;
        ///Do not share it, and use it to see your form.&lt;br/&gt;&lt;br/&gt;
        ///&lt;br/&gt;&lt;br/&gt;
        ///Kind regards,&lt;br/&gt;
        ///MyContractsGenerator Team.
        /// </summary>
        public static string Form_CollaboratorMailBody {
            get {
                return ResourceManager.GetString("Form_CollaboratorMailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MyContractsGenerator - We need some information, please fill this form .
        /// </summary>
        public static string Form_CollaboratorMailSubject {
            get {
                return ResourceManager.GetString("Form_CollaboratorMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Forms.
        /// </summary>
        public static string Form_label {
            get {
                return ResourceManager.GetString("Form_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mail already sent.
        /// </summary>
        public static string Form_MailAlreadySent {
            get {
                return ResourceManager.GetString("Form_MailAlreadySent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An email has been send to {0} {1}..
        /// </summary>
        public static string Form_MailedSentToCollaborator {
            get {
                return ResourceManager.GetString("Form_MailedSentToCollaborator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mail your collaborators.
        /// </summary>
        public static string Form_Mailing_Title {
            get {
                return ResourceManager.GetString("Form_Mailing_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please create jobs, binded collaborator in order to be able to send emails..
        /// </summary>
        public static string Form_NoRoleWithCollaborator {
            get {
                return ResourceManager.GetString("Form_NoRoleWithCollaborator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Send mail again.
        /// </summary>
        public static string Form_ReSendMail {
            get {
                return ResourceManager.GetString("Form_ReSendMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Check {0} answer(s).
        /// </summary>
        public static string Form_SeeAnswers {
            get {
                return ResourceManager.GetString("Form_SeeAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Send.
        /// </summary>
        public static string Form_SendForm {
            get {
                return ResourceManager.GetString("Form_SendForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Send form.
        /// </summary>
        public static string Form_SendMail {
            get {
                return ResourceManager.GetString("Form_SendMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mailing &amp; Collaborators answers.
        /// </summary>
        public static string FormMailing_label {
            get {
                return ResourceManager.GetString("FormMailing_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You seized forbidden characters which prevent the validation..
        /// </summary>
        public static string HttpRequestValidationException {
            get {
                return ResourceManager.GetString("HttpRequestValidationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This account has been locked, please try again.
        /// </summary>
        public static string Locked_Message {
            get {
                return ResourceManager.GetString("Locked_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Locked.
        /// </summary>
        public static string Locked_Title {
            get {
                return ResourceManager.GetString("Locked_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connexion.
        /// </summary>
        public static string Login_ConnexionButton {
            get {
                return ResourceManager.GetString("Login_ConnexionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid login or password.
        /// </summary>
        public static string Login_InvalidUserNameOrPassword {
            get {
                return ResourceManager.GetString("Login_InvalidUserNameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Login.
        /// </summary>
        public static string Login_Label {
            get {
                return ResourceManager.GetString("Login_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Login.
        /// </summary>
        public static string Login_PageTitle {
            get {
                return ResourceManager.GetString("Login_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password.
        /// </summary>
        public static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your password has been change. A nemail has been sent to you with the auto-generated password..
        /// </summary>
        public static string Login_PasswordChangeSuccess {
            get {
                return ResourceManager.GetString("Login_PasswordChangeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Forgot password ?.
        /// </summary>
        public static string Login_PasswordForgotten {
            get {
                return ResourceManager.GetString("Login_PasswordForgotten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The {0} field is requiered.
        /// </summary>
        public static string Login_RequiredField {
            get {
                return ResourceManager.GetString("Login_RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unknown login email.
        /// </summary>
        public static string Login_UnknownLogin {
            get {
                return ResourceManager.GetString("Login_UnknownLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Logout.
        /// </summary>
        public static string LoginPartial_Logout {
            get {
                return ResourceManager.GetString("LoginPartial_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à My profile.
        /// </summary>
        public static string LoginPartial_MyProfil {
            get {
                return ResourceManager.GetString("LoginPartial_MyProfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mailing.
        /// </summary>
        public static string Mailing_PageTitle {
            get {
                return ResourceManager.GetString("Mailing_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to logout from MyContractsGenerator ?.
        /// </summary>
        public static string Menu_LogoutConfirm {
            get {
                return ResourceManager.GetString("Menu_LogoutConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Close.
        /// </summary>
        public static string Modal_Close_Label {
            get {
                return ResourceManager.GetString("Modal_Close_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You are goin to add a new company to your application, do you want to continue ?.
        /// </summary>
        public static string Organization_AddConfirmationMessage {
            get {
                return ResourceManager.GetString("Organization_AddConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Company &quot;{0}&quot; successfully created.
        /// </summary>
        public static string Organization_Added {
            get {
                return ResourceManager.GetString("Organization_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add.
        /// </summary>
        public static string Organization_AddValidateButton {
            get {
                return ResourceManager.GetString("Organization_AddValidateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Administrators.
        /// </summary>
        public static string Organization_AdministratorsList_Label {
            get {
                return ResourceManager.GetString("Organization_AdministratorsList_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        public static string Organization_CancelButton {
            get {
                return ResourceManager.GetString("Organization_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to cancel the modifications ?.
        /// </summary>
        public static string Organization_CancelModal_Message {
            get {
                return ResourceManager.GetString("Organization_CancelModal_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit company.
        /// </summary>
        public static string Organization_Edit {
            get {
                return ResourceManager.GetString("Organization_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Company &quot;{0}&quot; successfully edited.
        /// </summary>
        public static string Organization_Edited {
            get {
                return ResourceManager.GetString("Organization_Edited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Company.
        /// </summary>
        public static string Organization_Label {
            get {
                return ResourceManager.GetString("Organization_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Company.
        /// </summary>
        public static string Organization_Modal_Header {
            get {
                return ResourceManager.GetString("Organization_Modal_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No organization selected.
        /// </summary>
        public static string Organization_MultiSelect_NonSelectedText {
            get {
                return ResourceManager.GetString("Organization_MultiSelect_NonSelectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New company.
        /// </summary>
        public static string Organization_New {
            get {
                return ResourceManager.GetString("Organization_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No active administrator found for this organization.
        /// </summary>
        public static string Organization_No_Admin_Message {
            get {
                return ResourceManager.GetString("Organization_No_Admin_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Companies.
        /// </summary>
        public static string Organization_PageTitle {
            get {
                return ResourceManager.GetString("Organization_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Company &quot;{0}&quot; has been removed.
        /// </summary>
        public static string Organization_RemoveNotification_Message {
            get {
                return ResourceManager.GetString("Organization_RemoveNotification_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure ?.
        /// </summary>
        public static string Organization_SuppressionModal_Header {
            get {
                return ResourceManager.GetString("Organization_SuppressionModal_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to delete the company &quot;{0}&quot; ? All linked administrator will be unbinded, all access revoked..
        /// </summary>
        public static string Organization_SuppressionModal_Message {
            get {
                return ResourceManager.GetString("Organization_SuppressionModal_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove company.
        /// </summary>
        public static string Organization_Tooltip_Remove {
            get {
                return ResourceManager.GetString("Organization_Tooltip_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Validate.
        /// </summary>
        public static string Organization_ValidateButton {
            get {
                return ResourceManager.GetString("Organization_ValidateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You are goin to add a new job to your project, do you want to continue ?.
        /// </summary>
        public static string Role_AddConfirmationMessage {
            get {
                return ResourceManager.GetString("Role_AddConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Job &quot;{0}&quot; successfully created.
        /// </summary>
        public static string Role_Added {
            get {
                return ResourceManager.GetString("Role_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Yes.
        /// </summary>
        public static string Role_AddValidateButton {
            get {
                return ResourceManager.GetString("Role_AddValidateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        public static string Role_CancelButton {
            get {
                return ResourceManager.GetString("Role_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to cancel the modifications?.
        /// </summary>
        public static string Role_CancelModal_Message {
            get {
                return ResourceManager.GetString("Role_CancelModal_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit job.
        /// </summary>
        public static string Role_Edit {
            get {
                return ResourceManager.GetString("Role_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Job &quot;{0}&quot; successfully edited.
        /// </summary>
        public static string Role_Edited {
            get {
                return ResourceManager.GetString("Role_Edited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This job label is already in use.
        /// </summary>
        public static string Role_ErrorIncorrectLabelAlreadyUsed {
            get {
                return ResourceManager.GetString("Role_ErrorIncorrectLabelAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Jobs.
        /// </summary>
        public static string Role_label {
            get {
                return ResourceManager.GetString("Role_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Job label :.
        /// </summary>
        public static string Role_Label_Name {
            get {
                return ResourceManager.GetString("Role_Label_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Job.
        /// </summary>
        public static string Role_Modal_Header {
            get {
                return ResourceManager.GetString("Role_Modal_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No job selected.
        /// </summary>
        public static string Role_MultiSelect_NonSelectedText {
            get {
                return ResourceManager.GetString("Role_MultiSelect_NonSelectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create job.
        /// </summary>
        public static string Role_New {
            get {
                return ResourceManager.GetString("Role_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New job.
        /// </summary>
        public static string Role_NewRole {
            get {
                return ResourceManager.GetString("Role_NewRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Manage your jobs.
        /// </summary>
        public static string Role_PageTitle {
            get {
                return ResourceManager.GetString("Role_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Job &quot;{0}&quot; has been removed.
        /// </summary>
        public static string Role_RemoveNotification_Message {
            get {
                return ResourceManager.GetString("Role_RemoveNotification_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure ?.
        /// </summary>
        public static string Role_SuppressionModal_Header {
            get {
                return ResourceManager.GetString("Role_SuppressionModal_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to delete the job &quot;{0}&quot; ? All linked collaborators will be unbind..
        /// </summary>
        public static string Role_SuppressionModal_Message {
            get {
                return ResourceManager.GetString("Role_SuppressionModal_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Validate.
        /// </summary>
        public static string Role_ValidateButton {
            get {
                return ResourceManager.GetString("Role_ValidateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove job.
        /// </summary>
        public static string Roler_Tooltip_RemoveRole {
            get {
                return ResourceManager.GetString("Roler_Tooltip_RemoveRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email send failed : {0}.
        /// </summary>
        public static string SendMailExceptionMessage {
            get {
                return ResourceManager.GetString("SendMailExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have unsaved changes, are you sure you wish to continue ?.
        /// </summary>
        public static string Shared_BeforeLeave_Message {
            get {
                return ResourceManager.GetString("Shared_BeforeLeave_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No.
        /// </summary>
        public static string Shared_Button_No {
            get {
                return ResourceManager.GetString("Shared_Button_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ok.
        /// </summary>
        public static string Shared_Button_Ok {
            get {
                return ResourceManager.GetString("Shared_Button_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Yes.
        /// </summary>
        public static string Shared_Button_Yes {
            get {
                return ResourceManager.GetString("Shared_Button_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occured.
        /// </summary>
        public static string Shared_ErrorModal_Header {
            get {
                return ResourceManager.GetString("Shared_ErrorModal_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Maximum length is {1} characters.
        /// </summary>
        public static string Shared_MessageError_MaxLength {
            get {
                return ResourceManager.GetString("Shared_MessageError_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The new password lenght must be between {0} and {1} .
        /// </summary>
        public static string Shared_MessageError_MinAndMaxLength {
            get {
                return ResourceManager.GetString("Shared_MessageError_MinAndMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This field is requiered.
        /// </summary>
        public static string Shared_RequiredField {
            get {
                return ResourceManager.GetString("Shared_RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Super Administrator.
        /// </summary>
        public static string SuperAdministrator_MenuTitle {
            get {
                return ResourceManager.GetString("SuperAdministrator_MenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hello,&lt;br/&gt;&lt;br/&gt;
        ///Your My Contracts Generator password reset request has been received.&lt;br/&gt;&lt;br/&gt;
        ///Your new password is: {0}&lt;br/&gt;&lt;br/&gt;
        ///You can now login to My Contracts Generator with this new password. &lt;br/&gt;&lt;br/&gt;
        ///Kind regards
        ///&lt;br/&gt;&lt;br/&gt;&lt;br/&gt;
        ///PS: You are receiving this e-mail because you, or someone using your e-mail address, has informed us of a forgotten My Contracts Generator password..
        /// </summary>
        public static string User_PasswordChange_MailBody {
            get {
                return ResourceManager.GetString("User_PasswordChange_MailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your My Contracts Generator password has been reset.
        /// </summary>
        public static string User_PasswordChange_MailSubject {
            get {
                return ResourceManager.GetString("User_PasswordChange_MailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hello,&lt;br/&gt;&lt;br/&gt;
        ///Your &lt;a href=&quot;{0}&quot;&gt;My Contracts Generator&lt;/a&gt; account was created on {1} by {2}.&lt;br/&gt;
        ///Login and password:&lt;br/&gt;&lt;br/&gt;
        ///E-mail: {3}&lt;br/&gt;
        ///Password: {4}&lt;br/&gt;
        ///You can now login to My Contracts Generator with this password and change it.&lt;br/&gt;&lt;br/&gt;
        ///Kind regards&lt;br/&gt;&lt;br/&gt;
        ///PS: You are receiving this e-mail because {2} created an account for you on My Contracts Generator. The password has been generated automatically..
        /// </summary>
        public static string User_PasswordCreate_MailBody {
            get {
                return ResourceManager.GetString("User_PasswordCreate_MailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your My Contracts Generator account has been created.
        /// </summary>
        public static string User_PasswordCreate_MailSubject {
            get {
                return ResourceManager.GetString("User_PasswordCreate_MailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure to want to reset your password?
        ///A new password will automatically be generated and sent by e-mail..
        /// </summary>
        public static string User_ResetPasswordConfirmationMessage {
            get {
                return ResourceManager.GetString("User_ResetPasswordConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reset your password.
        /// </summary>
        public static string User_ResetPasswordConfirmationTitle {
            get {
                return ResourceManager.GetString("User_ResetPasswordConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password change.
        /// </summary>
        public static string UserEditPassword_PageTitle {
            get {
                return ResourceManager.GetString("UserEditPassword_PageTitle", resourceCulture);
            }
        }
    }
}
