//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyContractsGenerator.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using MyContractsGenerator.Domain;
    
    public partial class MyContractsGeneratorEntities : DbContext
    {
        public MyContractsGeneratorEntities()
            : base("name=MyContractsGeneratorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<collaborator> collaborators { get; set; }
        public virtual DbSet<form> forms { get; set; }
        public virtual DbSet<question_type> question_type { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<answer> answers { get; set; }
        public virtual DbSet<question> questions { get; set; }
        public virtual DbSet<form_answer> form_answer { get; set; }
        public virtual DbSet<administrator> administrators { get; set; }
    }
}
